grails-app/domain/de/uni_heidelberg/iph/DiagnosticOrder.groovy
package de.uni_heidelberg.iph

class DiagnosticOrder {

   Date dateCreated

   Date lastUpdated

    /* Priority */
    public static final String PRIORITY_ROUTINE = "routine"

    public static final String PRIORITY_URGENT = "urgent"

    public static final List PRIORITY = [PRIORITY_ROUTINE, PRIORITY_URGENT]

    User requesterMedicalDoctor
//    User orderer

    //  To test the regular expression     https://regex101.com/
    // ^[R,S,T,G,N]-\d{5}-\d{2}
    String eNumber = ""

    String block = ""

    String patientName = " "

    static final String TUMOR_TYPE_MESENCHYMAL = "Mesenchymal Tumor"
    static final String TUMOR_TYPE_CARCINOMA = "Carcinoma"
    static final String TUMOR_TYPE_LYMPHOMA = "Lymphoma"
    static final String TUMOR_TYPE_LEUKEMIA = "Leukemia"
    static final String TUMOR_TYPE_OTHER = "Other"

    public static final List TUMOR_TYPE = [
        TUMOR_TYPE_MESENCHYMAL,
        TUMOR_TYPE_CARCINOMA,
        TUMOR_TYPE_LYMPHOMA,
        TUMOR_TYPE_LEUKEMIA,
        TUMOR_TYPE_OTHER
    ]

    String tumorType = TUMOR_TYPE_MESENCHYMAL

//    String sampleAndBlock = " "

    String reason = ""

    String supportingInformation = ""

    String barcode = ""

    /* Status */
    public static final String DRAFT = "draft"

    public static final String REQUESTED = "requested"

    public static final String ACCEPTED = "accepted"

    public static final String SUSPENDED = "suspended"

    /** In case of step non-conformity */
    public static final String PAUSED = "paused"

    public static final String IN_PROGRESS = "in-progress"

    public static final String LABORATORY_PREPARATION = "laboratoryPreparation"

    public static final String REVIEW_LABORATORY_PREPARATION = "reviewLaboratoryPreparation"

    public static final String REVIEW_DIAGNOSTIC_EVALUATION = "reviewDiagnosticEvaluation"

    public static final String REPORT_SIGNED = "reportSigned"

    public static final String REPORT_SENT = "reportSent"

    public static final String COMPLETED = "completed"

//    public static final String NON_CONFORMITY_DETECTED = "nonConformityDetected"

// Not implemented because there is not interest in suspend anything..
// If is not finished sucessfully or the patient dies, it is not paid..
//    public static final String SUSPENDED = "suspended"

    public static final String FAILED = "failed"

    // If the status is FAILED on some attempts, it may be set to REJECTED (not billed, in passnet)
    public static final String REJECTED = "rejected"

    public static final String CANCELLED = "cancelled"

    public static final String NON_CONFORMITY = "nonconformity"

    public static final List STATUS = [
//        DRAFT,
        REQUESTED,
        IN_PROGRESS,
//        ACCEPTED,
//        REVIEW_LABORATORY_PREPARATION,
//        REVIEW_DIAGNOSTIC_EVALUATION,
//        REJECTED,
//        FAILED,
//        REPORT_SIGNED,
//        REPORT_SENT,
        NON_CONFORMITY,
        COMPLETED,
        CANCELLED
    ]

//    //proposed | draft | planned | requested | received | accepted | in-progress | review | completed | cancelled | suspended | rejected | failed
////    String status = "requested"
//    String status = STATUS_REVIEW_LABORATORY_PREPARATION
String status = REQUESTED


//Code	Display	Definition
//routine	Routine	The order has a normal priority .
//urgent	Urgent	The order should be urgently.
//stat	Stat	The order is time-critical.
//asap	ASAP	The order should be acted on as soon as possible.
    String priority = PRIORITY_ROUTINE

    String note = " "

//    static hasMany = [Item: DiagnosticOrderItem]
//    static hasMany = [requestItem: RequestItem]

    static hasMany = [items: DiagnosticOrderItem,
//                      diagnosticOrderStatusEvent: DiagnosticOrderStatusEvent
                      events: DiagnosticOrderStatusEvent
                  ]

    static constraints = {
        tumorType(inList: TUMOR_TYPE)
        barcode(widget: 'textfield', blank: true, nullable: true)
        priority(inList: PRIORITY)
        status(inList: STATUS)
        note(widget: 'textarea', blank: true, nullable: true)
        reason(widget: 'textarea', blank: true, nullable: true)
        supportingInformation(widget: 'textarea', blank: true, nullable: true)
//        requesterMedicalDoctor(nullable: false)
        requesterMedicalDoctor(nullable: true)
//        assistantMedicalDoctor(nullable: false)
//        medicalDoctor(nullable: true)
    }

    static mapping = {
        events cascade:"all-delete-orphan", lazy:false
        items cascade:"all-delete-orphan", lazy:false
    }
}

grails-app/domain/de/uni_heidelberg/iph/Probe.groovy
package de.uni_heidelberg.iph

class Probe {

    public static final String HYBRIDIZATION_PROCEDURE_CISH = "CISH"
    public static final String HYBRIDIZATION_PROCEDURE_FISH = "FISH"
    public static final String HYBRIDIZATION_PROCEDURE_SPLIT_CISH = "split-CISH"
    public static final String HYBRIDIZATION_PROCEDURE_SPLIT_FISH = "split-FISH"
    public static final String HYBRIDIZATION_PROCEDURE_FUSION_FISH = "fusion-FISH"

    String name
    String code
    String description
//    List tissueType = ["Solid Tumoren", "Haemotolgie", "Weichteiltumoren"]
//    String cost

    String procedure
    String note

    Boolean available = true
    Boolean enabled = true

    Gene gene
    TissueType tissueType
    Manufacturer manufacturer

    // Mappings
    static belongsTo = [
            gene : Gene,
            tissueType: TissueType,
            manufacturer: Manufacturer
    ]

//    static def COMMENT = ["Backup bei Problemen mit CISH",
//                      "Backup bei Problemen mit RT-PCR",
//                      "Kopienzahl bei sol. Tumoren",
//                      "Burkitt-Lymphom u.a."]

    static def HIBRIDIZATION_PROCEDURE = [HYBRIDIZATION_PROCEDURE_CISH,
                                          HYBRIDIZATION_PROCEDURE_FISH,
                                          HYBRIDIZATION_PROCEDURE_SPLIT_CISH,
                                          HYBRIDIZATION_PROCEDURE_SPLIT_FISH,
                                          HYBRIDIZATION_PROCEDURE_FUSION_FISH]

    static constraints = {
        name()
        code(nullable: false)
        description(widget: 'textarea')
//        comment(inList: COMMENT)
        procedure(inList: HIBRIDIZATION_PROCEDURE)
        note(widget: 'textarea', nullable: true)
        available()
        enabled()
        gene()
        tissueType(nullable: true)
        manufacturer()
    }

    String toString() {
        return name + " - " + code
    }
}

grails-app/controllers/de/uni_heidelberg/iph/DiagnosticOrderController.groovy
package de.uni_heidelberg.iph

import grails.converters.*

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
import java.awt.image.BufferedImage
import javax.imageio.ImageIO

// TODO REMOVE when solve windows HACK
import java.util.regex.Matcher;

import com.google.zxing.MultiFormatWriter
import com.google.zxing.client.j2se.MatrixToImageWriter
import com.google.zxing.common.BitMatrix
import com.google.zxing.BarcodeFormat
import com.google.zxing.EncodeHintType


@Transactional(readOnly = true)
class DiagnosticOrderController {

    def workflowService
    def mailNotificationService

    static scaffold = true

//MedicalDoctor
//	setStatusUpdate(Requested)
//	setStatusUpdate(Completed)
//TechnicalAssistant
//	setStatusUpdate(InProgress)
//	setStatusUpdate(ReviewLaboratoryPreparation)
//AssistantMedicalDoctor
//	setStatusUpdate(ReviewDiagnosticEvaluation)
//	setStatusUpdate(Failed)

//proposed | draft | planned | requested | received | accepted | in-progress | review | completed | cancelled | suspended | rejected | failed


    MultiFormatWriter barCodeWriter = new MultiFormatWriter()

    def test() {
        mailNotificationService.sendMail("cristiano_manuel@hotmail.com", "sera?!", "dsfsdfsdafsdafsdfsdf")
        render "yes"
    }

    void renderImage(response, String data, int width, int height, BarcodeFormat format = BarcodeFormat.QR_CODE) {
        Hashtable hints = [(EncodeHintType.CHARACTER_SET): 'UTF8']
        BitMatrix bitMatrix = barCodeWriter.encode(data, format, width, height, hints)
        MatrixToImageWriter.writeToStream(bitMatrix, "png", response.outputStream)
    }

    private File renderImageToFile(File file, String data, int width, int height, BarcodeFormat format = BarcodeFormat.QR_CODE) {
        Hashtable hints = [(EncodeHintType.CHARACTER_SET): 'UTF8']
        BitMatrix bitMatrix = barCodeWriter.encode(data, format, width, height, hints)
        MatrixToImageWriter.writeToFile(bitMatrix, "png", file)
        return file
    }

//    http://generator.barcoding.com/
//    http://barcode.tec-it.com/en
//    https://www.dlsoft.com/barcode_types/identify_a_barcode.htm
//    http://www.scandit.com/products/barcode-scanner/symbologies/code-128/
//    http://www.barcodefaq.com/BarcodeMatch/
//def barcode(String data, String formate, int width, int height) {
def barcode() {

//String formatIPH = "EAN_13"
String formatIPH = "CODE_128" //  p/20Ju8b9Ey/SRkUbxIxZA
//String data = "4006381333931"
//
//    int width = 200
//    int height = 50

        String fileSeparator = System.getProperty("file.separator")
//        String destinationDirectory = "/Users/tanovsky/wip/pathoHL7/images-repo/"
//        String destinationDirectory = "~/images-repo/"
//        String destinationDirectory = System.getProperty("user.home") + "/pathoHL7imagesRepository/fish-cish/"

        String destinationDirectory = System.getProperty("user.home") + fileSeparator +
                                      "tmp-barcodes" + fileSeparator

        File temporaryDestinationDirectory = new File(destinationDirectory)
        temporaryDestinationDirectory.mkdirs()

    BarcodeFormat format = BarcodeFormat.valueOf(formatIPH)
    File file = File.createTempFile("temp-barcode", ".png", temporaryDestinationDirectory)

    String path = renderImageToFile(file, params.data, params.width as int, params.height as int, format as BarcodeFormat)

    BufferedImage originalImage = ImageIO.read(new File(path));
    ByteArrayOutputStream baos = new ByteArrayOutputStream();

    def fileext = path.substring(path.indexOf(".")+1, path.length())

    ImageIO.write( originalImage, fileext, baos );
    baos.flush();

    byte[] img = baos.toByteArray();
    baos.close();
    response.setHeader('Content-length', img.length.toString())
    response.contentType = "image/" + fileext // or the appropriate image content type
    response.outputStream << img
    response.outputStream.flush()
}

def search() {

        println "params " + params

        def taskList = DiagnosticOrder.createCriteria().list () {
            if ( params.query ) {
                println "estou aki?! __-----------------------------"
                String queryValue = params.query.trim()
                or {
                    ilike("eNumber", "%${queryValue}%")
                    ilike("block", "%${queryValue}%")
                    ilike("supportingInformation", "%${queryValue}%")
                    ilike("status", "%${queryValue}%")
                    ilike("priority", "%${queryValue}%")
                }
            }
        }

        println "taskList : " + taskList

//        def taskList = DiagnosticOrder.createCriteria().list (params) {
//            if ( params.query ) {
//                ilike("eNumber", "%${params.query}%")
//            }
//        }

//        def taskList = DiagnosticOrder.findAllByENumber("%${params.query}%")
//        model = [
//            diagnosticOrderInstanceList: taskList,
//            diagnosticOrderInstanceTotal: 10,
//            queryTerm: params.query
//        ]

//        model = [
//            diagnosticOrderInstanceList: DiagnosticOrder.list( params ),
//            diagnosticOrderInstanceTotal: DiagnosticOrder.count()
//        ]

        Map myModel = [
            diagnosticOrderInstanceList: taskList,
            diagnosticOrderInstanceTotal: 10,
            query: params.query
        ]

        return myModel
}

//    def list() {
//        params.max = Math.min(params.max ? params.int('max') : 5, 100)
//
//        def taskList = Task.createCriteria().list (params) {
//            if ( params.query ) {
//                ilike("description", "%${params.query}%")
//            }
//        }
//
//        [taskInstanceList: taskList, taskInstanceTotal: taskList.totalCount]
//    }
//

def getImage(){
    def path = params.filepath
    //returns an image to display
    BufferedImage originalImage = ImageIO.read(new File(path));
    ByteArrayOutputStream baos = new ByteArrayOutputStream();

    def fileext = path.substring(path.indexOf(".")+1, path.length())

    ImageIO.write( originalImage, fileext, baos );
    baos.flush();

    byte[] img = baos.toByteArray();
    baos.close();
    response.setHeader('Content-length', img.length.toString())
    response.contentType = "image/"+fileext // or the appropriate image content type
    response.outputStream << img
    response.outputStream.flush()
}

    List<String> nextDiagnosticStatusUpdateAvailable2(String status, String role) {
        String nextStatus = "draft"

//        List<String> availableStatus = DiagnosticOrder.DRAFT
        List<String> availableStatus

//    public static final String REQUESTER_MEDICAL_DOCTOR = "RequesterMedicalDoctor"
//    public static final String TECHNICAL_ASSISTANT = "TechnicalAssistant"
//    public static final String MEDICAL_DOCTOR = "MedicalDoctor"
//    public static final String ASSISTANT_MEDICAL_DOCTOR = "AssistantMedicalDoctor"
//    public static final String MANAGER = "Manager"
//    public static final String ACCOUNTANT = "Accountant"
//    public static final String ADMINISTRATOR = "Administrator"

        switch (role) {
                case User.REQUESTER_MEDICAL_DOCTOR:
                    switch (status) {
                        case DiagnosticOrder.REQUESTED:
                            availableStatus = [
                                DiagnosticOrder.REQUESTED,
                                DiagnosticOrder.CANCELLED]
                        break
                        default:
                            availableStatus = ["draft"]
                    }
                break
                case User.TECHNICAL_ASSISTANT:
                case User.MEDICAL_DOCTOR:
                case User.ASSISTANT_MEDICAL_DOCTOR:
                case User.MANAGER:
                case User.ACCOUNTANT:
                case User.ADMINISTRATOR:
                default:
                    println "none"
                break
        }

//        return ["requested", "canceled"]
        return availableStatus
    }

    String nextDiagnosticStatusUpdateAvailable(String status, String role) {

        println "status : " + status

        println "role : " + role

        String nextStatus = "noStatusAvailable"

        if (role == "TechnicalAssistant") {
            if (status == "requested") {
                nextStatus = "in-progress"
            } else if (status == "in-progress") {
                nextStatus = "reviewLaboratoryPreparation"
            }
        } else if (role == "AssistantMedicalDoctor") {
            if (status == "reviewLaboratoryPreparation") {
                nextStatus = "reviewDiagnosticEvaluation"
            }
        } else if (role == "MedicalDoctor") {
            if (status == "reviewDiagnosticEvaluation") {
                nextStatus = "completed"
            }
        }
        return nextStatus
    }

    String renameFile(String filename) {
        println "renaming file... ${filename}"
        return "newFilename"
    }

    def Date getNowUTC() {
        Calendar cal = Calendar.getInstance()
        cal.setTimeZone(TimeZone.getTimeZone("UTC"))
        System.out.println(cal.toString())
        Date now = cal.getTime()
        return now
      }

        @Transactional
    def updateDOStatus(DiagnosticOrder diagnosticOrderInstance) {
        println diagnosticOrderInstance

//        def res = params as JSON
//        res.prettyPrint = true
//        render res
        diagnosticOrderInstance.eNumber = diagnosticOrderInstance.eNumber.replaceAll("/","")
        diagnosticOrderInstance.save()

        // TODO implement this at a service
//        DiagnosticOrderStatusEvent dose = new DiagnosticOrderStatusEvent()
//        dose.status = params.status
//        dose.actor = session.user
//        dose.description = "some descriptiosn.."
//        dose.dateTime = getNowUTC()
//        dose.diagnosticOrder = diagnosticOrderInstance
//

grails-app/views/diagnosticOrder/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main">
        <g:set var="entityName" value="${message(code: 'diagnosticOrder.label', default: 'DiagnosticOrder')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"/>
        <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
        <!--
        <script src="http://igorescobar.github.io/jQuery-Mask-Plugin/js/jquery.mask.min.js"></script>
        -->
        <g:javascript src="jquery.mask.min.js" />

        <script>
            $(function() {
            $( "#tabs" ).tabs();
            });
        </script>
    </head>
    <body>

        <a href="#create-diagnosticOrder" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
<!--
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
-->
                <li><g:link class="list" action="index"><g:message code="default.diagnostic.order.list" args="[entityName]" /></g:link></li>
                </ul>
            </div>
            <div id="create-diagnosticOrder" class="content scaffold-create" role="main">
            <!--
                <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            -->
                <h1><g:message code="default.diagnostic.order.create" default="Create Diagnostic Order" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${diagnosticOrderInstance}">
                <ul class="errors" role="alert">
                    <g:eachError bean="${diagnosticOrderInstance}" var="error">
                        <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                        </g:eachError>
                </ul>
            </g:hasErrors>

            <g:form url="[resource:diagnosticOrderInstance, action:'saveGeneListRequest']" >
                <fieldset id="barcodeform" class="form">
                    <g:render template="form"/>
                </fieldset>

                <div id="tabs" style="border-color:transparent;border-width:10px;">
                    <ul>
                        <li><a href="#tabs-1">CISH/FISH</a></li>
<!--
                        <li><a href="#tabs-2">Mutationsanalysen</a></li>
                        <li><a href="#tabs-3">Translokationsaanalysen</a></li>
                        <li><a href="#tabs-4">...</a></li>
-->
                    </ul>
                    <div id="tabs-1">

                        <table>
                        <thead>
                            <th></th>
                            <th><g:message code="default.gene" default="Gene" /></th>
                            <th><g:message code="default.procedure" default="Procedure" /></th>
                            <th><g:message code="default.locus" default="Locus" /></th>
                            <th><g:message code="default.tissue.type" default="Tissue type" /></th>
                            <!--
                            <th>Note</th>
                            -->
                        </thead>
                            <tbody>
                                <g:each in="${probeList}" status="jj" var="probe">
                                    <tr>
                                        <td>
                                            <g:checkBox title="${probe.gene.name}" name='probes' checked='${false}' value="${""+probe.id}"/>
                                        </td>
                                        <td>${probe.gene.name}</td>
                                        <td>${probe.procedure}</td>
                                        <td>${probe.gene.locus}</td>
                                        <td>${probe?.tissueType?.name}</td>
                                        <!--
                                        <td>${probe.note}</td>
                                        -->
                                    </tr>
                                </g:each>
                                <tr>
                                    <td>

                                    </td>
                                    <td>

                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
<!--
                    <div id="tabs-2">
                        <p>TODO</p>
                    </div>
                    <div id="tabs-3">
                        <p>TODO</p>
                    </div>
                    <div id="tabs-4">
                        <p>TODO</p>
                    </div>
-->
                </div>




                <fieldset class="buttons">
                    <g:submitButton onclick="return isValid(document.getElementById('eNumber').value) && isAnyCheckBoxSelected()" name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                    </fieldset


                </g:form>
        </div>
<script>

// TODO Improve and replace by Regular expression
function isValid(eNumber){
    var isValido = true;
/*
    var currentTime = new Date();
    var actualYear = currentTime.getFullYear()- 2000;
    var allowedSymbols = "erdh"
    var eNumberParts = eNumber.split("-");
    isValido = ((eNumberParts.length==3)
         && (eNumberParts[0].length==1)
         && (allowedSymbols.indexOf(eNumberParts[0])>=0)
         && (eNumberParts[1].length==5)
         && (eNumberParts[2].length==2)
         && (eNumberParts[2] <= actualYear)
);
if (!isValido) {
         alert("Not a valid eNumber!");
}
*/
    return isValido;
}

function isAnyCheckBoxSelected(){
//  alert("entrei");
    var checkedAtLeastOne = false;
    $('input[type="checkbox"]').each(function() {
//        alert("" + $(this));
        if ($(this).is(":checked")) {
            checkedAtLeastOne = true;
        }
    });
    if (!checkedAtLeastOne) {
        alert("Please select at least one gene");
    }
    return checkedAtLeastOne;
}

/*
function validateForm() {

}
*/

$(document).ready(function () {
  //called when key is pressed in textbox
  $("#eNumber").keypress(function (e) {
//  alert(e.which);
     //if the letter is not digit then display error and don't type anything
     if (
     e.which == 60 ||    // '<'
     e.which == 13       //  carriage return
//		 && e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)
) {
        //display error message
        $("#errmsg").html("Digits Only").show().fadeOut("slow");
               return false;
    }
   });
});

//var options =  {onKeyPress: function(cep, e, field, options){
//  this.value = this.value.toUpperCase();
//}};


$('#eNumber').mask('Z/00/000000', {
    translation: {
        'Z': {
            pattern: /[ERSTGN]/, optional: true
        }
    }, placeholder: "_/__/______"});
    
//    ,onKeyPress: function (value, event) {
//    alert(event.currentTarget.value);
//        event.currentTarget.value = value.toUpperCase();
//        alert(value.toUpperCase());
//    },
//placeholder: " /  /      "}
//);


//    $('#eNumber').keyup(function() {
//
//        this.value = this.value.toUpperCase();
//    });



</script>
    </body>
</html>

grails-app/views/diagnosticOrder/index.gsp
<%@ page import="de.uni_heidelberg.iph.DiagnosticOrder" %>
<%@ page import="de.uni_heidelberg.iph.User" %>
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main">
        <g:set var="entityName" value="${message(code: 'diagnosticOrder.label', default: 'DiagnosticOrder')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-diagnosticOrder" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <g:ifUserHasRole roles="${User.REQUESTER_MEDICAL_DOCTOR}">
                <li><g:link class="create" action="create"><g:message code="default.diagnostic.order.create" default="Create Diagnostic Order" /></g:link></li>
                </g:ifUserHasRole>
            </ul>
        </div>
        <div style="padding-left: 100px;padding-right: 100px;" id="list-diagnosticOrder" class="content scaffold-list" role="main">
           <h1>${message(code: 'default.diagnostic.order.list', default: 'Diagnostic Orders list')}</h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
                <table>
                    <thead>
                        <tr>
                            <g:sortableColumn property="eNumber" title="${message(code: 'default.eNumber', default: 'eNumber')}" />
                            <g:sortableColumn property="eNumber" title="${message(code: 'default.block', default: 'Block')}" />
                            <g:sortableColumn property="priority" title="${message(code: 'default.priority', default: 'Priority')}" />
                            <g:sortableColumn property="dateCreated" title="${message(code: 'default.date.created', default: 'Date Created')}" />
                            <g:sortableColumn property="lastUpdated" title="${message(code: 'default.date.last.update', default: 'Last Updated')}" />
<!--
                                                <g:sortableColumn property="note" title="${message(code: 'diagnosticOrder.note.label', default: 'Note')}" />

                                                <g:sortableColumn property="reason" title="${message(code: 'diagnosticOrder.reason.label', default: 'Reason')}" />

                                                <g:sortableColumn property="supportingInformation" title="${message(code: 'diagnosticOrder.supportingInformation.label', default: 'Supporting Information')}" />
-->
                            <g:sortableColumn property="supportingInformation" title="${message(code: 'default.provisional.diagnostic', default: 'Provision Diagnosis')}" />
                            <th><g:message code="diagnosticOrder.requester.label" default="Requester" /></th>
                            <g:sortableColumn property="status" title="${message(code: 'default.status', default: 'Status')}" />
                        </tr>
                    </thead>
                    <tbody>
                        <g:each in="${diagnosticOrderInstanceList}" status="i" var="diagnosticOrderInstance">
                            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
                                <tr class="${(i % 2) == 0 ? 'even' : 'odd'}, clickable-row" data-href="${createLink(controller: "diagnosticOrder", action:'items', params: [id: diagnosticOrderInstance.id])}">
                                <td>${fieldValue(bean: diagnosticOrderInstance, field: "eNumber")}</td>
                                <td>${fieldValue(bean: diagnosticOrderInstance, field: "block")}</td>
                                <td>${fieldValue(bean: diagnosticOrderInstance, field: "priority")}</td>
                                <td><g:formatDate date="${diagnosticOrderInstance.dateCreated}" type="datetime" style="LONG" timeStyle="SHORT"/></td>
                                <td><g:formatDate date="${diagnosticOrderInstance.lastUpdated}" type="datetime" style="LONG" timeStyle="SHORT"/></td>
<!--
                                <td>${fieldValue(bean: diagnosticOrderInstance, field: "note")}</td>
                                <td>${fieldValue(bean: diagnosticOrderInstance, field: "supportingInformation")}</td>
-->
                                <td>${fieldValue(bean: diagnosticOrderInstance, field: "supportingInformation")}</td>
                                <td>${fieldValue(bean: diagnosticOrderInstance, field: "requesterMedicalDoctor.login")}</td>
                                <td><g:message code="default.fish.status.${diagnosticOrderInstance?.status}" /></td>
                                
                            </tr>
                        </g:each>
                    </tbody>
                </table>
            <div class="pagination">
                <g:paginate total="${diagnosticOrderInstanceCount ?: 0}" />
            </div>
            <div style="min-height: 400px;min-height: 400px;height: 400px;"></div>
        </div>
    </body>
</html>