grails-app/domain/de/uni_heidelberg/iph/Gene.groovy
package de.uni_heidelberg.iph

class Gene {
    
    String name
    String alias
    String locus
//    String description

    static hasMany = [probe: Probe]

    static constraints = {
        name blank: false, nullable: false
        alias blank: true, nullable: true
        locus blank: false, nullable: false
//        description(widget:'textarea')
    }
}

grails-app/controllers/de/uni_heidelberg/iph/GeneController.groovy
package de.uni_heidelberg.iph

class GeneController {

    static scaffold = true

//    def beforeInterceptor = [action: this.&auth, except: 'login']
    def beforeInterceptor = [action: this.&auth]

    // defined with private scope, so it's not considered an action
  private auth() {
    if (![User.ADMINISTRATOR, User.MANAGER].contains(session?.user?.role)) {
      flash.message = "You must be an administrator to perform that task."
      redirect(action:"entry", controller: "user")
      return false
    }
  }
}

grails-app/views/gene/_form.gsp
<%@ page import="de.uni_heidelberg.iph.Gene" %>



<div class="fieldcontain ${hasErrors(bean: geneInstance, field: 'name', 'error')} required">
	<label for="name">
		<g:message code="gene.name.label" default="Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="name" required="" value="${geneInstance?.name}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: geneInstance, field: 'alias', 'error')} ">
	<label for="alias">
		<g:message code="gene.alias.label" default="Alias" />
		
	</label>
	<g:textField name="alias" value="${geneInstance?.alias}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: geneInstance, field: 'locus', 'error')} required">
	<label for="locus">
		<g:message code="gene.locus.label" default="Locus" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="locus" required="" value="${geneInstance?.locus}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: geneInstance, field: 'probe', 'error')} ">
	<label for="probe">
		<g:message code="gene.probe.label" default="Probe" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${geneInstance?.probe?}" var="p">
    <li><g:link controller="probe" action="show" id="${p.id}">${p?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="probe" action="create" params="['gene.id': geneInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'probe.label', default: 'Probe')])}</g:link>
</li>
</ul>


</div>

grails-app/views/gene/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'gene.label', default: 'Gene')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-gene" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-gene" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${geneInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${geneInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:geneInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/gene/edit.gsp
<%@ page import="de.uni_heidelberg.iph.Gene" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'gene.label', default: 'Gene')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-gene" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-gene" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${geneInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${geneInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:geneInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${geneInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/gene/index.gsp
<%@ page import="de.uni_heidelberg.iph.Gene" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'gene.label', default: 'Gene')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-gene" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-gene" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="name" title="${message(code: 'gene.name.label', default: 'Name')}" />
					
						<g:sortableColumn property="alias" title="${message(code: 'gene.alias.label', default: 'Alias')}" />
					
						<g:sortableColumn property="locus" title="${message(code: 'gene.locus.label', default: 'Locus')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${geneInstanceList}" status="i" var="geneInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${geneInstance.id}">${fieldValue(bean: geneInstance, field: "name")}</g:link></td>
					
						<td>${fieldValue(bean: geneInstance, field: "alias")}</td>
					
						<td>${fieldValue(bean: geneInstance, field: "locus")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${geneInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/gene/show.gsp
<%@ page import="de.uni_heidelberg.iph.Gene" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'gene.label', default: 'Gene')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-gene" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-gene" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list gene">
			
				<g:if test="${geneInstance?.name}">
				<li class="fieldcontain">
					<span id="name-label" class="property-label"><g:message code="gene.name.label" default="Name" /></span>
					
						<span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${geneInstance}" field="name"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${geneInstance?.alias}">
				<li class="fieldcontain">
					<span id="alias-label" class="property-label"><g:message code="gene.alias.label" default="Alias" /></span>
					
						<span class="property-value" aria-labelledby="alias-label"><g:fieldValue bean="${geneInstance}" field="alias"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${geneInstance?.locus}">
				<li class="fieldcontain">
					<span id="locus-label" class="property-label"><g:message code="gene.locus.label" default="Locus" /></span>
					
						<span class="property-value" aria-labelledby="locus-label"><g:fieldValue bean="${geneInstance}" field="locus"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${geneInstance?.probe}">
				<li class="fieldcontain">
					<span id="probe-label" class="property-label"><g:message code="gene.probe.label" default="Probe" /></span>
					
						<g:each in="${geneInstance.probe}" var="p">
						<span class="property-value" aria-labelledby="probe-label"><g:link controller="probe" action="show" id="${p.id}">${p?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:geneInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${geneInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>