grails-app/domain/de/uni_heidelberg/iph/User.groovy
package de.uni_heidelberg.iph

class User {

    public static final String REQUESTER_MEDICAL_DOCTOR = "RequesterMedicalDoctor"
    public static final String TECHNICAL_ASSISTANT = "TechnicalAssistant"
    public static final String MEDICAL_DOCTOR = "MedicalDoctor"
    public static final String ASSISTANT_MEDICAL_DOCTOR = "AssistantMedicalDoctor"
    public static final String MANAGER = "Manager"
    public static final String ACCOUNTANT = "Accountant"
    public static final String ADMINISTRATOR = "Administrator"

    String login
    String password
    String role = MEDICAL_DOCTOR

    String name
    String mobile
    String tel
    String email
    String address

    static constraints = {
		login(blank: false, size: 3..20, unique:true)
		password(blank: false, size: 4..20, password:true)
                role(inList:[
                        REQUESTER_MEDICAL_DOCTOR,
                        TECHNICAL_ASSISTANT,
                        MEDICAL_DOCTOR,
                        ASSISTANT_MEDICAL_DOCTOR,
                        MANAGER,
                        ACCOUNTANT,
                        ADMINISTRATOR
                    ])
		name()
		mobile()
		tel(nullable: true)
                email(email:true, blank:false)
		address(nullable: true)
    }

    String toString(){
            name + " (" +role + ")"
    }

   static mapping = {
      table 'users'
      password column: '`password`'
   }
}

grails-app/controllers/de/uni_heidelberg/iph/UserController.groovy
package de.uni_heidelberg.iph

import grails.converters.JSON
import grails.transaction.Transactional

class UserController {

    def workflowService

    def beforeInterceptor = [action: this.&auth, only: ["create", "list", "delete", "edit", "show"]]

    // defined with private scope, so it's not considered an action
    private auth() {
        if (![User.ADMINISTRATOR, User.MANAGER].contains(session?.user?.role)) {
            flash.message = "You must be an administrator to perform that task."
//            redirect(action:"entry", controller: "user")
            redirect(action:"entry", controller: "user")
//            redirect(action:"login", controller: "user")
            return false
        }
    }

    def index() {
        redirect(action:"list", params:params) }

        // the delete, save and update actions only accept POST requests
        static allowedMethods = [delete:'POST', save:'POST', update:'POST']



        def teste() {
            render(view:'/user/teste')
//            render(view:'/user/login');
        }

	def entry() {
            params.max = Math.min( params.max ? params.max.toInteger() : 0,  100)

            //        [ userInstanceList: User.list( params ), userInstanceTotal: User.count() ]
            //		render(view:'/user/login', model:[ userInstanceList: User.list( params ), userInstanceTotal: User.count() ]);
            //[ userInstanceList: User.list( params ), userInstanceTotal: User.count() ]

            Calendar cal=Calendar.getInstance();
            int month = cal.get(Calendar.MONTH);

            def now = new Date()
            def nextLimit = now + 31
            //		def reserv = Reservation.findAllByDateBetween( now, nextLimit )
            //		def reserv = Reservation.findAllByUser7hOrUser8hOrUser9hOrUser10hOrUser11hOrUser12hOrUser13hOrUser14hOrUser15hOrUser16hOrUser17hOrUser18hOrUser19h(session?.user,session?.user,session?.user,session?.user,session?.user,session?.user,session?.user,session?.user,session?.user,session?.user,session?.user,session?.user,session?.user);
            //		def reserv = Reservation.findAllByUser7hLike(session?.user);  // funca
            //		def reserv = Reservation.findAllByUser7hOrUser8h(session?.user, session?.user);  // funca
//		def reserv = Reservation.findAllByUser7hOrUser8hOrUser9h(session?.user, session?.user, session?.user);
            //		def reserv = Reservation.findAllByUser7hOrUser8hOrUser9h(session?.user,session?.user,session?.user);

//		def criteria = Reservation.createCriteria()

//            def allDiagnosticOrders = DiagnosticOrder.list(params)
            def allDiagnosticOrders = DiagnosticOrderItem.list()
            List notCompletedOrders = []
            List notCompletedOrderItems = []
            int contador = 0
            allDiagnosticOrders.each {
                switch (session?.user.role) {
                    case User.REQUESTER_MEDICAL_DOCTOR:
                        if (((it.diagnosticOrder.requesterMedicalDoctor?.id == session.user.id)) &&
                            (!(it.status in [DiagnosticOrder.COMPLETED, DiagnosticOrder.CANCELLED]))) {
                                notCompletedOrders.add(it.diagnosticOrder)
                                notCompletedOrderItems.add(it)
                        }
                    break
                    case User.TECHNICAL_ASSISTANT:
                    case User.ASSISTANT_MEDICAL_DOCTOR:
                    case User.MEDICAL_DOCTOR:
                        if ((it.status != DiagnosticOrder.COMPLETED) &
                            (it.status in workflowService.diagnosticOrderItemStatusHandledByRole(session?.user.role))) {
                            notCompletedOrders.add(it.diagnosticOrder)
                            notCompletedOrderItems.add(it)
                        }
                    break
                    case User.ADMINISTRATOR:
                        if ((it.status != DiagnosticOrder.COMPLETED)) {
                            notCompletedOrders.add(it.diagnosticOrder)
                            notCompletedOrderItems.add(it)
                        }
                    break
                }
            }
            notCompletedOrders.unique()
            notCompletedOrderItems.unique()

            def allDiagnosticOrderItemStatusEvents = DiagnosticOrderItemStatusEvent.withCriteria {
                eq('user', session?.user)
                'between'('dateCreated', new Date() - grailsApplication.config.application.fish.history.daysBefore, new Date())
                order("dateCreated", "desc")
            }

            List latestPerformedDiagnosticOrder = []
            List latestPerformedDiagnosticOrderItems = []
            allDiagnosticOrderItemStatusEvents.each {
//                latestPerformedDiagnosticOrder.add(it.diagnosticOrderItem.diagnosticOrder)
                latestPerformedDiagnosticOrderItems.add(it.diagnosticOrderItem)
            }
//            latestPerformedDiagnosticOrder.unique()
            latestPerformedDiagnosticOrderItems.unique()

//            latestPerformedDiagnosticOrderItems.each {
//                it.status = DiagnosticOrderItemService.lastStatusEvent(it)
//            }

            render view:'/user/entry',
                model: [diagnosticOrderItemsInstanceList: notCompletedOrderItems, diagnosticOrderItemsInstanceTotal: notCompletedOrderItems.size(),
                            myLatestDiagnosticOrderItemsInstanceList: latestPerformedDiagnosticOrderItems, latestPerformedDiagnosticOrderItemsTotal: latestPerformedDiagnosticOrderItems.size()]

//            render ([diagnosticOrderInstanceList: notCompletedOrders, diagnosticOrderInstanceTotal: notCompletedOrders.size(),
//                    myLatestDiagnosticOrderInstanceList: latestPerformedDiagnosticOrder, latestPerformedDiagnosticOrderTotal: latestPerformedDiagnosticOrder.size()]) as JSON


//            render ([diagnosticOrderItemsInstanceList: notCompletedOrderItems, diagnosticOrderInstanceTotal: notCompletedOrderItems.size(),
//                            myLatestDiagnosticOrderItemsInstanceList: latestPerformedDiagnosticOrderItems, latestPerformedDiagnosticOrderItemsTotal: latestPerformedDiagnosticOrderItems.size()]) as JSON
	}

	def entryOriginal() {
            params.max = Math.min( params.max ? params.max.toInteger() : 0,  100)

            //        [ userInstanceList: User.list( params ), userInstanceTotal: User.count() ]
            //		render(view:'/user/login', model:[ userInstanceList: User.list( params ), userInstanceTotal: User.count() ]);
            //[ userInstanceList: User.list( params ), userInstanceTotal: User.count() ]

            Calendar cal=Calendar.getInstance();
            int month = cal.get(Calendar.MONTH);


            def now = new Date()
            def nextLimit = now + 31
            //		def reserv = Reservation.findAllByDateBetween( now, nextLimit )
            //		def reserv = Reservation.findAllByUser7hOrUser8hOrUser9hOrUser10hOrUser11hOrUser12hOrUser13hOrUser14hOrUser15hOrUser16hOrUser17hOrUser18hOrUser19h(session?.user,session?.user,session?.user,session?.user,session?.user,session?.user,session?.user,session?.user,session?.user,session?.user,session?.user,session?.user,session?.user);
            //		def reserv = Reservation.findAllByUser7hLike(session?.user);  // funca
            //		def reserv = Reservation.findAllByUser7hOrUser8h(session?.user, session?.user);  // funca
//		def reserv = Reservation.findAllByUser7hOrUser8hOrUser9h(session?.user, session?.user, session?.user);
            //		def reserv = Reservation.findAllByUser7hOrUser8hOrUser9h(session?.user,session?.user,session?.user);

//		def criteria = Reservation.createCriteria()

//            def allDiagnosticOrders = DiagnosticOrder.list(params)
            def allDiagnosticOrders = DiagnosticOrderItem.list()
            List notCompletedOrders = []
            int contador = 0
            allDiagnosticOrders.each {
                switch (session?.user.role) {
                    case User.REQUESTER_MEDICAL_DOCTOR:
                        if (((it.diagnosticOrder.requesterMedicalDoctor?.id == session.user.id)) &&
                            (!(it.status in [DiagnosticOrder.COMPLETED, DiagnosticOrder.CANCELLED]))) {
                                notCompletedOrders.add(it.diagnosticOrder)
                        }
                    break
                    case User.TECHNICAL_ASSISTANT:
                    case User.ASSISTANT_MEDICAL_DOCTOR:
                    case User.MEDICAL_DOCTOR:
                        if ((it.status != DiagnosticOrder.COMPLETED) &
                            (it.status in workflowService.diagnosticOrderItemStatusHandledByRole(session?.user.role))) {
                            notCompletedOrders.add(it.diagnosticOrder)
                        }
                    break
                    case User.ADMINISTRATOR:
                        if ((it.status != DiagnosticOrder.COMPLETED)) {
                            notCompletedOrders.add(it.diagnosticOrder)
                        }
                    break
                }
            }
            notCompletedOrders.unique()

            def allDiagnosticOrderItemStatusEvents = DiagnosticOrderItemStatusEvent.withCriteria {
                eq('user', session?.user)
                'between'('dateCreated', new Date() - grailsApplication.config.application.fish.history.daysBefore, new Date())
            }

            List latestPerformedDiagnosticOrder = []
            allDiagnosticOrderItemStatusEvents.each {
                latestPerformedDiagnosticOrder.add(it.diagnosticOrderItem.diagnosticOrder)
            }
            latestPerformedDiagnosticOrder.unique()

            return [diagnosticOrderInstanceList: notCompletedOrders, diagnosticOrderInstanceTotal: notCompletedOrders.size(),

grails-app/views/user/create.gsp
<%@ page import="de.uni_heidelberg.iph.User" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="layout" content="main" />
        <title>Create User</title>         
    </head>
    <body>

        
        <div class="nav">
            <ul>
                <li><a class="home" href="${createLinkTo(dir:'')}">Home</a></li>
                <li><g:link class="list" action="list">User List</g:link></li>
            </ul>
        </div>  
        
        <div class="body">
            <h1>Create User</h1>
            <g:if test="${flash.message}">
            <div class="message">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${userInstance}">
            <div class="errors">
                <g:renderErrors bean="${userInstance}" as="list" />
            </div>
            </g:hasErrors>
            <g:form action="save" method="post" >
                <div class="dialog">
                    <table>
                        <tbody>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="login">Login:</label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean:userInstance,field:'login','errors')}">
                                    <input type="text" maxlength="20" id="login" name="login" value="${fieldValue(bean:userInstance,field:'login')}"/>
                                </td>
                            </tr> 
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="password">Password:</label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean:userInstance,field:'password','errors')}">
                                    <input type="password" maxlength="20" id="password" name="password" value="${fieldValue(bean:userInstance,field:'password')}"/>
                                </td>
                            </tr> 
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="role">Role:</label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean:userInstance,field:'role','errors')}">
                                    <g:select id="role" name="role" from="${userInstance.constraints.role.inList}" value="${userInstance.role}" ></g:select>
                                </td>
                            </tr> 
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="name">Name:</label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean:userInstance,field:'name','errors')}">
                                    <input type="text" id="name" name="name" value="${fieldValue(bean:userInstance,field:'name')}"/>
                                </td>
                            </tr>

                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="mobile">Email:</label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean:userInstance,field:'email','errors')}">
                                    <input type="text" id="email" name="email" value="${fieldValue(bean:userInstance,field:'email')}"/>
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="mobile">Mobile:</label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean:userInstance,field:'mobile','errors')}">
                                    <input type="text" id="mobile" name="mobile" value="${fieldValue(bean:userInstance,field:'mobile')}"/>
                                </td>
                            </tr> 
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="tel">Tel:</label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean:userInstance,field:'tel','errors')}">
                                    <input type="text" id="tel" name="tel" value="${fieldValue(bean:userInstance,field:'tel')}"/>
                                </td>
                            </tr> 
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="address">Address:</label>
                                </td>

								<td valign="top" class="value ${hasErrors(bean:userInstance,field:'address','errors')}">
									<textarea id="address" name="address" rows="5" cols="60" >
										${fieldValue(bean:userInstance, field:'address' )}
									</textarea>
								</td>

<!--
                                <td valign="top" class="value ${hasErrors(bean:userInstance,field:'address','errors')}">
                                    <input type="text" id="address" name="address" value="${fieldValue(bean:userInstance,field:'address')}"/>
                                </td>
-->
                            </tr> 
                        
                        </tbody>
                    </table>
                </div>
                <div class="buttons">
                    <span class="button"><input class="save" type="submit" value="Create" /></span>
                </div>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/user/edit.gsp
<%@ page import="de.uni_heidelberg.iph.User" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="layout" content="main" />
        <title>Edit User</title>
    </head>
    <body>
        <div class="nav">
            <ul>
                <li><a class="home" href="${createLinkTo(dir:'')}">Home</a></li>
                <li><g:link class="list" action="list">User List</g:link></li>
                <li><g:link class="create" action="create">New User</g:link></li>
            </ul>
        </div>
        <div class="body">
            <h1>Edit User</h1>
            <g:if test="${flash.message}">
            <div class="message">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${userInstance}">
            <div class="errors">
                <g:renderErrors bean="${userInstance}" as="list" />
            </div>
            </g:hasErrors>
            <g:form method="post" >
                <input type="hidden" name="id" value="${userInstance?.id}" />
                <input type="hidden" name="version" value="${userInstance?.version}" />
                <div class="dialog">
                    <table>
                        <tbody>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="login">Login:</label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean:userInstance,field:'login','errors')}">
                                    <input type="text" maxlength="20" id="login" name="login" value="${fieldValue(bean:userInstance,field:'login')}"/>
                                </td>
                            </tr> 
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="password">Password:</label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean:userInstance,field:'password','errors')}">
                                    <input type="password" maxlength="20" id="password" name="password" value="${fieldValue(bean:userInstance,field:'password')}"/>
                                </td>
                            </tr> 
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="role">Role:</label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean:userInstance,field:'role','errors')}">
                                    <g:select id="role" name="role" from="${userInstance.constraints.role.inList}" value="${userInstance.role}" ></g:select>
                                </td>
                            </tr> 
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="name">Name:</label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean:userInstance,field:'name','errors')}">
                                    <input type="text" id="name" name="name" value="${fieldValue(bean:userInstance,field:'name')}"/>
                                </td>
                            </tr> 
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="mobile">Mobile:</label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean:userInstance,field:'mobile','errors')}">
                                    <input type="text" id="mobile" name="mobile" value="${fieldValue(bean:userInstance,field:'mobile')}"/>
                                </td>
                            </tr> 
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="tel">Tel:</label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean:userInstance,field:'tel','errors')}">
                                    <input type="text" id="tel" name="tel" value="${fieldValue(bean:userInstance,field:'tel')}"/>
                                </td>
                            </tr> 
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="address">Address:</label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean:userInstance,field:'address','errors')}">
                                    <input type="text" id="address" name="address" value="${fieldValue(bean:userInstance,field:'address')}"/>
                                </td>
                            </tr> 
                        
                        </tbody>
                    </table>
                </div>
                <div class="buttons">
                    <span class="button"><g:actionSubmit class="save" value="Update" /></span>
                    <span class="button"><g:actionSubmit class="delete" onclick="return confirm('Are you sure?');" value="Delete" /></span>
                </div>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/user/list.gsp
<%@ page import="de.uni_heidelberg.iph.User" %>

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="layout" content="main" />
        <title>User List</title>
    </head>
    <body>
        <div class="nav">
            <ul>
                <li><a class="home" href="${createLinkTo(dir:'')}">Home</a></li>
                <li><g:link class="create" action="create">New User</g:link></li>
            </ul>
        </div>    
        <div class="body">
            <h1>User List</h1>
            <g:if test="${flash.message}">
            <div class="message">${flash.message}</div>
            </g:if>
            <div class="list">
                <table>
                    <thead>
                        <tr>
                        
                   	        <g:sortableColumn property="id" title="Id" />
                        
                   	        <g:sortableColumn property="login" title="Login" />
<!--                        
                   	        <g:sortableColumn property="password" title="Password" />
-->                        
                   	        <g:sortableColumn property="role" title="Role" />
                        
                   	        <g:sortableColumn property="name" title="Name" />
                        
                   	        <g:sortableColumn property="tel" title="Tel" />
                        
                        </tr>
                    </thead>
                    <tbody>
                    <g:each in="${userInstanceList}" status="i" var="userInstance">
                        <tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
                        
                            <td><g:link action="show" id="${userInstance.id}">${fieldValue(bean:userInstance, field:'id')}</g:link></td>
                        
                            <td>${fieldValue(bean:userInstance, field:'login')}</td>
                            
<!--                            
                        
                            <td>${fieldValue(bean:userInstance, field:'password')}</td>
-->                        
                            <td>${fieldValue(bean:userInstance, field:'role')}</td>
                        
                            <td>${fieldValue(bean:userInstance, field:'name')}</td>
                        
                            <td>${fieldValue(bean:userInstance, field:'tel')}</td>
                        
                        </tr>
                    </g:each>
                    </tbody>
                </table>
            </div>

            
			<div class="pagination">
				<g:paginate total="${userInstanceTotal ?: 0}" />
			</div>
        </div>
    </body>
</html>

grails-app/views/user/show.gsp
<%@ page import="de.uni_heidelberg.iph.User" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="layout" content="main" />
        <title>Show User</title>
    </head>
    <body>
        <div class="nav">
            <ul>
                <li><a class="home" href="${createLinkTo(dir:'')}">Home</a></li>
                <li><g:link class="list" action="list">User List</g:link></li>
                <li><g:link class="create" action="create">New User</g:link></li>
            </ul>
        </div>
        <div class="body">
            <h1>Show User</h1>
            <g:if test="${flash.message}">
            <div class="message">${flash.message}</div>
            </g:if>
            <div class="dialog">
                <table>
                    <tbody>

                    
                        <tr class="prop">
                            <td valign="top" class="name">Id:</td>
                            
                            <td valign="top" class="value">${fieldValue(bean:userInstance, field:'id')}</td>
                            
                        </tr>
                    
                        <tr class="prop">
                            <td valign="top" class="name">Login:</td>
                            
                            <td valign="top" class="value">${fieldValue(bean:userInstance, field:'login')}</td>
                            
                        </tr>
                    
                        <tr class="prop">
                            <td valign="top" class="name">Password:</td>
                            
                            <td valign="top" class="value">${fieldValue(bean:userInstance, field:'password')}</td>
                            
                        </tr>
                    
                        <tr class="prop">
                            <td valign="top" class="name">Role:</td>
                            
                            <td valign="top" class="value">${fieldValue(bean:userInstance, field:'role')}</td>
                            
                        </tr>
                    
                        <tr class="prop">
                            <td valign="top" class="name">Name:</td>
                            
                            <td valign="top" class="value">${fieldValue(bean:userInstance, field:'name')}</td>
                            
                        </tr>
                    
                        <tr class="prop">
                            <td valign="top" class="name">Mobile:</td>
                            
                            <td valign="top" class="value">${fieldValue(bean:userInstance, field:'mobile')}</td>
                            
                        </tr>
                    
                        <tr class="prop">
                            <td valign="top" class="name">Tel:</td>
                            
                            <td valign="top" class="value">${fieldValue(bean:userInstance, field:'tel')}</td>
                            
                        </tr>
                    
                        <tr class="prop">
                            <td valign="top" class="name">Address:</td>
                            
                            <td valign="top" class="value">${fieldValue(bean:userInstance, field:'address')}</td>
                            
                        </tr>
                    
                    </tbody>
                </table>
            </div>
            <div class="buttons">
                <g:form>
                    <input type="hidden" name="id" value="${userInstance?.id}" />
                    <span class="button"><g:actionSubmit class="edit" value="Edit" /></span>
                    <span class="button"><g:actionSubmit class="delete" onclick="return confirm('Are you sure?');" value="Delete" /></span>
                </g:form>
            </div>
        </div>
    </body>
</html>

grails-app/views/user/teste.gsp
<html>
	<head>
		<meta name="layout" content="main" />
		<title>Logindfdfgdfg</title>
	</head>
	<body>

		<div class="body">
			<h1>Login</h1>
			<g:if test="${flash.message}">
				<div class="message">${flash.message}</div>
			</g:if>
			
			<g:form controller="user" action="authenticate" method="post" >
				<div class="dialog">
					<input type="hidden" name="cName" value="${cName}" >
					<input type="hidden" name="aName" value="${aName}" >
					<table>
						<tbody>
							<tr class="prop">
								<td class="name">
									<label for="login">Login:</label>
								</td>
								<td>
									<input type="text" id="login" name="login"/>
								</td>
							</tr>

							<tr class="prop">
								<td class="name">
									<label for="password">Password:</label>
								</td>
								<td>
									<input type="password" id="password" name="password"/>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
				<div class="buttons">
					<span class="button">
						<input class="save" type="submit" value="Login" />
					</span>
				</div>
			</g:form>
		</div>

	</body>
</html>